version: '3'

services:

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"

  driver-service:
    build: ./driver-service
    ports:
      - "8082:8082"

  trip-service:
    build: ./trip-service
    ports:
      - "8083:8083"

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"

  payment-service:
    build: ./payment-service
    ports:
      - "8085:8085"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"